HeatTemplateFormatVersion: '2012-12-12'
Description: |
  Template which starts tilemill
Parameters:
  KeyName:
    Type: String
  InstanceType:
    Type: String
  ImageId:
    Type: String
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Standard firewall rules
      SecurityGroupIngress:
      - {IpProtocol: icmp, FromPort: '-1', ToPort: '-1', CidrIp : 0.0.0.0/0}
      - {IpProtocol: tcp, FromPort: '22', ToPort: '22', CidrIp: 0.0.0.0/0}
      - {IpProtocol: tcp, FromPort: '80', ToPort: '80', CidrIp: 0.0.0.0/0}
  all_in_one:
    Type: OS::Nova::Server
    Properties:
      ImageId: {Ref: ImageId}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      SecurityGroups: [{Ref: SecurityGroup}]
      UserData:
        Fn::Base64: |
            #!/bin/bash -v
	    wget https://github.com/stevage/tilemill-server/raw/master/install.sh -O /tmp/install_tilemill.sh
	    chmod +x /tmp/install_tilemill.sh
	    /tmp/install_tilemill.sh
